# Ruff 简单配置
target-version = "py312"
line-length = 88

[lint]
# 只启用基础规则
select = [
    "E",    # pycodestyle 错误
    "W",    # pycodestyle 警告  
    "F",    # pyflakes
    "I",    # isort (导入排序)
    "UP",   # pyupgrade (Python版本升级)
]

# 忽略的规则
ignore = [
    "E501",  # 行过长
]

# 排除目录
exclude = [
    ".git",
    ".venv", 
    "__pycache__",
    "build",
    "dist",
]

[format]
# 使用双引号
quote-style = "double"

[lint.isort]
# 项目的第一方模块
known-first-party = ["minimal_agentic"]